messenger_project-main/messenger_project-main/messenger_app/urls.py
# messenger_app/urls.py
from django.urls import path
from .views import (
    UserListView,
    EditProfileView,
    UserProfileDetailView,
    ChatWithUserView,
    ChatListView, SendMessageView, EditMessageView, DeleteMessageView, GroupChatCreateView, GroupChatDetailView,
    SendGroupMessageView,
)

app_name = 'messenger_app'

urlpatterns = [
    path('user-list/', UserListView.as_view(), name='user-list'),
    path('profile/', UserProfileDetailView.as_view(), name='profile'),
    path('chat/<str:username>/', ChatWithUserView.as_view(), name='chat-with-user'),
    path('edit-profile/', EditProfileView.as_view(), name='edit-profile'),
    path('chats/', ChatListView.as_view(), name='chat-list'),
    path('send-message/<str:username>/', SendMessageView.as_view(), name='send-message'),
    path('edit-message/<int:message_id>/', EditMessageView.as_view(), name='edit-message'),
    path('delete-message/<int:message_id>/', DeleteMessageView.as_view(), name='delete-message'),
    path('group-chat-create/', GroupChatCreateView.as_view(), name='group-chat-create'),
    path('group-chats/<int:pk>/', GroupChatDetailView.as_view(), name='group-chat-detail'),
    path('send-group-message/<int:chat_id>/', SendGroupMessageView.as_view(), name='send-group-message'),
]

messenger_project-main/messenger_project-main/messenger_project/urls.py
# messenger_project/urls.py

from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.views import LogoutView
from django.urls import include, path
from messenger_app.views import CustomLoginView, CustomRegisterView
from messenger_app.routing import websocket_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include('messenger_app.urls')),
    path('login/', CustomLoginView.as_view(), name='login'),
    path('register/', CustomRegisterView.as_view(), name='register'),
    path('logout/', LogoutView.as_view(next_page='login'), name='logout'),
    path('ws/', include(websocket_urlpatterns)),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

messenger_project-main/messenger_project-main/messenger_app/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse


class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    avatar = models.ImageField(upload_to='avatars/', null=True, blank=True)
    first_name = models.CharField(max_length=30, null=True, blank=True)
    last_name = models.CharField(max_length=30, null=True, blank=True)

    def __str__(self):
        return self.user.username


class Chat(models.Model):
    CHAT_TYPES = (
        ('group', 'Group Chat'),
        ('private', 'Private Chat'),
    )

    name = models.CharField(max_length=255)
    type = models.CharField(max_length=10, choices=CHAT_TYPES, default='private')
    members = models.ManyToManyField(UserProfile, related_name='chats')

    def __str__(self):
        return f"{self.name} ({self.get_type_display()})"

    def get_chat_display_name(self):
        if self.type == 'group':
            if self.name:
                return self.name
            else:
                return ", ".join([member.user.username for member in self.members.all()])
        elif self.type == 'private':
            members_names = [member.user.username for member in self.members.all()]
            return ', '.join(members_names)
        else:
            return "Неизвестный чат"

    def get_members_display(self):
        return ", ".join([member.user.username for member in self.members.all()])


class Message(models.Model):
    sender = models.ForeignKey(UserProfile, on_delete=models.CASCADE)
    chat = models.ForeignKey(Chat, on_delete=models.CASCADE, related_name='messages')
    content = models.TextField()
    recipient = models.ForeignKey(UserProfile, on_delete=models.CASCADE, related_name='recipient_messages', null=True, blank=True)
    timestamp = models.DateTimeField(auto_now_add=True)

    def get_absolute_url(self):
        return reverse('user_profile_detail', args=[str(self.id)])

    def __str__(self):
        return self.sender.user.username if self.sender and self.sender.user else "No User"

messenger_project-main/messenger_project-main/messenger_app/forms.py
from django import forms
from .models import UserProfile, Chat, Message


# Форма для редактирования профиля

class UserProfileForm(forms.ModelForm):
    first_name = forms.CharField(label='Имя', max_length=100)
    last_name = forms.CharField(label='Фамилия', max_length=100)

    class Meta:
        model = UserProfile
        fields = ['first_name', 'last_name', 'avatar']
        labels = {
            'avatar': 'Аватар',
        }
        widgets = {
            'avatar': forms.FileInput(attrs={'accept': 'image/*'}),
        }

    def __init__(self, *args, **kwargs):
        super(UserProfileForm, self).__init__(*args, **kwargs)
        self.fields['avatar'].required = False


# Форма для чата

class ChatForm(forms.ModelForm):
    members = forms.ModelMultipleChoiceField(
        queryset=UserProfile.objects.all(),
        widget=forms.CheckboxSelectMultiple
    )

    class Meta:
        model = Chat
        fields = ['name', 'members']


# Форма редактирования сообщения

class MessageForm(forms.ModelForm):
    class Meta:
        model = Message
        fields = ['content']


# Форма для создания группового чата

class GroupChatCreationForm(forms.ModelForm):
    class Meta:
        model = Chat
        fields = ['name', 'members']


# Форма для отправки сообщения в групповом чате

class GroupMessageForm(forms.ModelForm):
    class Meta:
        model = Message
        fields = ['content', 'recipient']

    def __init__(self, *args, **kwargs):
        super(GroupMessageForm, self).__init__(*args, **kwargs)
        if 'chat' in self.fields and self.instance.chat.type == 'group':
            self.fields['recipient'].widget = forms.HiddenInput()

messenger_project-main/messenger_project-main/messenger_app/views.py
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.http import HttpResponseRedirect, JsonResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.views import View
from django.views.generic import ListView, UpdateView, TemplateView
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from rest_framework import status
from rest_framework.response import Response
from rest_framework.views import APIView

from .models import UserProfile, Chat, Message
from .forms import UserProfileForm, MessageForm, GroupChatCreationForm
from django.contrib.auth.models import User
from django.urls import reverse, reverse_lazy
from django.contrib import messages

from .serializers import MessageSerializer


# ПРОФИЛЬ

# Просмотр профиля

class UserProfileDetailView(View):
    template_name = 'profile_detail.html'

    def get(self, request, *args, **kwargs):
        user_profile, created = UserProfile.objects.get_or_create(user=request.user)
        user_form = UserProfileForm(instance=user_profile)
        return render(request, self.template_name, {'user_profile': user_profile, 'user_form': user_form})


# Редактирование профиля

@method_decorator(login_required, name='dispatch')
class EditProfileView(UpdateView):
    model = UserProfile
    form_class = UserProfileForm
    template_name = 'edit_profile.html'
    success_url = '/api/profile'

    def get_object(self, queryset=None):
        return self.request.user.userprofile

    def form_valid(self, form):
        response = super().form_valid(form)
        user_profile = form.save(commit=False)
        user_profile.user.first_name = form.cleaned_data['first_name']
        user_profile.user.last_name = form.cleaned_data['last_name']
        user_profile.user.save()
        messages.success(self.request, 'Профиль успешно обновлен.')
        return response


# СООБЩЕНИЯ

# Отправка сообщения

class SendMessageView(View):
    template_name = 'send_message.html'

    def get_or_create_private_chat(self, sender, recipient):
        chat = Chat.objects.filter(members=sender).filter(members=recipient).filter(type='private').first()
        if chat is not None:
            return chat

        chat = Chat.objects.create(type='private')
        chat.members.add(sender, recipient)
        return chat

    def post(self, request, username):
        sender = request.user.userprofile
        recipient = get_object_or_404(User, username=username)
        recipient_profile, created = UserProfile.objects.get_or_create(user=recipient)
        content = request.POST.get('content', '')

        chat = self.get_or_create_private_chat(sender, recipient_profile)

        message = Message.objects.create(sender=sender, chat=chat, content=content, recipient=recipient_profile)

        # Отладочный вывод:
        print("Sending a message...")
        print("Messages:", Message.objects.filter(chat=chat).order_by('timestamp'))

        return render(request, 'chat_with_user.html', {'recipient_profile': recipient_profile,
                                                       'messages': Message.objects.filter(chat=chat).order_by(
                                                           'timestamp')})


# Редактирование сообщения

@method_decorator(login_required, name='dispatch')
class EditMessageView(View):
    template_name = 'edit_message.html'

    def get(self, request, message_id):
        message = get_object_or_404(Message, id=message_id, sender=request.user.userprofile)
        form = MessageForm(instance=message)
        return render(request, self.template_name, {'form': form, 'message_id': message_id})

    def post(self, request, message_id):
        message = get_object_or_404(Message, id=message_id, sender=request.user.userprofile)
        form = MessageForm(request.POST, instance=message)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('messenger_app:chat-with-user', args=[message.recipient.user.username]))
        return render(request, self.template_name, {'form': form, 'message_id': message_id})


# Удаление сообщения

@method_decorator(login_required, name='dispatch')
class DeleteMessageView(View):
    template_name = 'delete_message.html'

    def get(self, request, message_id):
        message = get_object_or_404(Message, id=message_id, sender=request.user.userprofile)
        return render(request, self.template_name,
                      {'message_id': message_id, 'recipient_username': message.recipient.user.username})

    def post(self, request, message_id):
        message = get_object_or_404(Message, id=message_id, sender=request.user.userprofile)
        recipient_username = message.recipient.user.username
        message.delete()
        return HttpResponseRedirect(reverse('messenger_app:chat-with-user', args=[recipient_username]))


# Отправка сообщения в групповой чат

class SendGroupMessageView(APIView):
    def post(self, request, chat_id, *args, **kwargs):
        chat = get_object_or_404(Chat, pk=chat_id, type='group')

        if request.user.userprofile not in chat.members.all():
            return Response({'status': 'Failed to send group message',
                             'errors': {'detail': 'You are not a member of this group chat.'}},
                            status=status.HTTP_403_FORBIDDEN)

        content = request.data.get('content', '')

        message = Message.objects.create(
            sender=request.user.userprofile,
            content=content,
            chat=chat,
            recipient=None
        )

        serializer = MessageSerializer(message)
        data = serializer.data

        sender_data = {
            'id': message.sender.id,
            'username': message.sender.user.username,
            'avatar': str(message.sender.avatar) if message.sender.avatar else None,
            'first_name': message.sender.first_name,
            'last_name': message.sender.last_name,
        }

        if message.recipient:
            recipient_data = {
                'id': message.recipient.id,
                'username': message.recipient.user.username,
                'avatar': str(message.recipient.avatar) if message.recipient.avatar else None,
                'first_name': message.recipient.first_name,
                'last_name': message.recipient.last_name,
            }
        else:
            recipient_data = {}

        data['sender'] = sender_data
        data['recipient'] = recipient_data

        return Response(data, status=status.HTTP_201_CREATED)


# ЧАТЫ

# Просмотр чатов

@method_decorator(login_required, name='dispatch')
class ChatListView(TemplateView):
    template_name = 'chat_list.html'

    def get_context_data(self, **kwargs):
        user_profile = self.request.user.userprofile
        chats = Chat.objects.filter(members=user_profile)
        chat_members = [
            {'chat': chat, 'chat_member': chat.members.exclude(id=user_profile.id).first()}
            for chat in chats
        ]

        for chat_member in chat_members:
            chat = chat_member['chat']
            if not chat.name:
                if chat.is_group_chat:
                    chat.name = "Групповой чат"
                else:
                    chat.name = ", ".join(
                        [member.user.username for member in chat.members.all() if member != user_profile])
                chat.save()

        context = {'chat_members': chat_members, 'user_profile': user_profile}
        return context


# Cоздание группового чата

@method_decorator(login_required, name='dispatch')
class GroupChatCreateView(View):
    template_name = 'group_chat_create.html'

    def get(self, request, *args, **kwargs):
        form = GroupChatCreationForm()
        return render(request, self.template_name, {'form': form})

    def post(self, request, *args, **kwargs):
        form = GroupChatCreationForm(request.POST)
        if form.is_valid():
            group_chat = Chat.objects.create(type='group', name=form.cleaned_data['name'])

            group_chat.members.add(request.user.userprofile, *form.cleaned_data['members'])

            return JsonResponse({'status': 'success', 'redirect_url': reverse_lazy('messenger_app:group-chat-detail',
                                                                                   kwargs={'pk': group_chat.id})})

        return JsonResponse({'status': 'error', 'errors': form.errors}, status=400)


# Просмотр группового чата

@method_decorator(login_required, name='dispatch')
class GroupChatDetailView(View):
    template_name = 'group_chat_detail.html'

    def get(self, request, pk):
        group_chat = Chat.objects.get(pk=pk)
        send_group_message_url = reverse('messenger_app:send-group-message', kwargs={'chat_id': pk})
        form = MessageForm()
        return render(request, self.template_name,
                      {'group_chat': group_chat, 'send_group_message_url': send_group_message_url, 'form': form})


# Чат с пользователем

class ChatWithUserView(View):
    template_name = 'chat_with_user.html'

    def get_or_create_private_chat(self, sender, recipient):
        chat = Chat.objects.filter(members=sender).filter(members=recipient).filter(type='private').first()
        if chat is not None:
            return chat

        # Если чат не найден, попробуем найти его в обратном порядке
        chat = Chat.objects.filter(members=recipient).filter(members=sender).filter(type='private').first()
        if chat is not None:
            return chat

        # Если чат не найден, создаем новый
        chat = Chat.objects.create(type='private')
        chat.members.add(sender, recipient)
        return chat

    def get(self, request, username):
        recipient = get_object_or_404(UserProfile, user__username=username)
        sender = request.user.userprofile

messenger_project-main/messenger_project-main/messenger_app/templates/base_generic.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}">
    <title>{% block title %}Messenger App{% endblock %}</title>
</head>
<body>
    <nav class="navbar">
        <ul class="nav-list">
            {% if user.is_authenticated %}
                <li><a class="nav-link" href="{% url 'messenger_app:chat-list' %}">Чаты</a></li>
                <li><a class="nav-link" href="{% url 'messenger_app:user-list' %}">Пользователи</a></li>
                <li><a class="nav-link" href="{% url 'messenger_app:profile' %}">Профиль</a></li>
                <li><a class="nav-link" href="{% url 'logout' %}">Выйти</a></li>
            {% else %}
                <li><a class="nav-link" href="{% url 'login' %}">Войти</a></li>
                <li><a class="nav-link" href="{% url 'register' %}">Регистрация</a></li>
            {% endif %}
        </ul>
    </nav>
    <div>
        {% block content %}{% endblock %}
    </div>
</body>
</html>

messenger_project-main/messenger_project-main/messenger_app/templates/chat_with_user.html
{% extends 'base_generic.html' %}
{% load static %}

{% block title %}Chat with {{ recipient_profile.user.username }}{% endblock %}

{% block content %}
  <link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}?v={{ timestamp }}">


  <div class="container">
    <h2>Чат с пользователем {{ recipient_profile.user.username }}</h2>

    <div id="chat-messages">
      {% if messages %}
        {# Отладочный вывод: #}
        <script>
          console.log('Messages:', {{ messages|safe }});
        </script>

        {% for message in messages %}
          <div class="message" data-message-id="{{ message.id }}">
            <div class="avatar">
              {% if message.sender.avatar %}
                <img src="{{ message.sender.avatar.url }}" alt="{{ message.sender.user.username }}">
              {% else %}
                <div class="no-avatar">{{ message.sender.user.username|first|upper }}</div>
              {% endif %}
            </div>

            <div class="message-content">
              <p><strong>{{ message.sender.user.username }}:</strong> {{ message.content }}</p>
              <span>{{ message.timestamp|date:"Y-m-d H:i:s" }}</span>

              {% if message.sender == request.user.userprofile %}
                <div class="message-actions">
                  <a href="{% url 'messenger_app:edit-message' message.id %}" class="edit-link">Редактировать</a>
                  <a href="{% url 'messenger_app:delete-message' message.id %}" class="delete-link">Удалить</a>
                </div>
              {% endif %}
            </div>
          </div>
        {% endfor %}

      {% else %}
        <p>Сообщений нет</p>
      {% endif %}
    </div>

    <form id="message-form" method="post" action="{% url 'messenger_app:send-message' username=recipient_profile.user.username %}">
      {% csrf_token %}
      <textarea name="content" rows="4" cols="50" required></textarea>
      <br>
      <button type="submit">Отправить сообщение</button>
    </form>
  </div>

<script>
  document.addEventListener('DOMContentLoaded', function() {
    var messages = document.querySelectorAll('.message');

    messages.forEach(function(message) {
      message.addEventListener('mouseover', function() {
        var actions = this.querySelector('.message-actions');
        if (actions) {
          actions.style.display = 'block';
        }
      });

      message.addEventListener('mouseout', function() {
        var actions = this.querySelector('.message-actions');
        if (actions) {
          actions.style.display = 'none';
        }
      });

      var actions = message.querySelector('.message-actions');
      if (actions) {
        var editLink = actions.querySelector('.edit-link');
        var deleteLink = actions.querySelector('.delete-link');

        editLink.addEventListener('click', function(event) {
          event.preventDefault();
          var messageId = message.dataset.messageId;
          // Реализуйте логику редактирования сообщения здесь, например, через AJAX запрос.
          console.log('Edit message clicked for message with ID:', messageId);
        });

        deleteLink.addEventListener('click', function(event) {
          event.preventDefault();
          var messageId = message.dataset.messageId;
          // Реализуйте логику удаления сообщения здесь, например, через AJAX запрос.
          console.log('Delete message clicked for message with ID:', messageId);
        });
      }
    });
  });
</script>



{% endblock %}

messenger_project-main/messenger_project-main/messenger_app/templates/delete_message.html
<!-- В templates/messenger_app/delete_message.html -->

{% extends 'base_generic.html' %}
{% load static %}

{% block title %}Delete Message{% endblock %}

{% block content %}
  <link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}">

  <div class="container">
    <h2>Delete Message</h2>
    <form method="post" action="{% url 'messenger_app:delete-message' message_id=message_id %}">
      {% csrf_token %}
      <p>Are you sure you want to delete this message?</p>
      <button type="submit">Delete</button>
      <a href="{% url 'messenger_app:chat-with-user' username=recipient_username %}">Cancel</a>
    </form>
  </div>
{% endblock %}

messenger_project-main/messenger_project-main/messenger_app/templates/edit_message.html
<!-- В templates/messenger_app/edit_message.html -->

{% extends 'base_generic.html' %}
{% load static %}

{% block title %}Edit Message{% endblock %}

{% block content %}
  <link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}">

  <div class="container">
    <h2>Edit Message</h2>
    <form method="post" action="{% url 'messenger_app:edit-message' message_id=message_id %}">
      {% csrf_token %}
      {{ form.as_p }}
      <button type="submit">Save changes</button>
    </form>
  </div>
{% endblock %}

messenger_project-main/messenger_project-main/messenger_app/templates/group_chat_detail.html
{% extends 'base_generic.html' %}
{% load static %}

{% block title %}Групповой чат: {{ group_chat.name }}{% endblock %}

{% block content %}
  <link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}?v={{ timestamp }}">

  <div class="container">
    <h2>Групповой чат: {{ group_chat.name }}</h2>

    <div id="chat-messages" data-edit-message-url="{% url 'messenger_app:edit-message' 0 %}">
      {% if messages %}
        {% for message in messages %}
          <div class="message" data-message-id="{{ message.id }}">
            <div class="avatar">
              {% if message.sender.avatar %}
                <img src="{{ message.sender.avatar.url }}" alt="{{ message.sender.user.username }}">
              {% else %}
                <div class="no-avatar">{{ message.sender.user.username|first|upper }}</div>
              {% endif %}
            </div>
            <div class="message-content">
              <p><strong>{{ message.sender.user.username }}:</strong> {{ message.content }}</p>
              <span>{{ message.timestamp|date:"Y-m-d H:i:s" }}</span>
              {% if message.sender == request.user.userprofile %}
                <div class="message-actions">
                  <a href="{% url 'messenger_app:edit-message' message.id %}" class="edit-link">Редактировать</a>
                  <a href="{% url 'messenger_app:delete-message' message.id %}" class="delete-link">Удалить</a>
                </div>
              {% endif %}
            </div>
          </div>
        {% endfor %}
      {% else %}
        <p>Сообщений нет</p>
      {% endif %}
    </div>

    <form id="message-form" data-chat-id="{{ group_chat.id }}" method="post" action="{% url 'messenger_app:send-group-message' group_chat.id %}">
      {% csrf_token %}
      <textarea name="content" rows="4" cols="50" required></textarea>
      <br>
      <button type="submit">Отправить сообщение</button>
    </form>
  </div>

  <script>
    document.addEventListener('DOMContentLoaded', function() {
      var messages = document.querySelectorAll('.message');
      var editMessageUrl = document.getElementById('chat-messages').getAttribute('data-edit-message-url');
      var deleteMessageUrl = `{% url 'messenger_app:delete-message' 0 %}`;

      var chatMessages = document.getElementById('chat-messages');
      if (!chatMessages) {
        console.error('Element with ID "chat-messages" not found.');
        return;
      }

      messages.forEach(function(message) {
        message.addEventListener('mouseover', function() {
          var actions = this.querySelector('.message-actions');
          if (actions) {
            actions.style.display = 'block';
          }
        });

        message.addEventListener('mouseout', function() {
          var actions = this.querySelector('.message-actions');
          if (actions) {
            actions.style.display = 'none';
          }
        });

        var actions = message.querySelector('.message-actions');
        if (actions) {
          var editLink = actions.querySelector('.edit-link');
          var deleteLink = actions.querySelector('.delete-link');

          editLink.addEventListener('click', function(event) {
            event.preventDefault();
            var messageId = message.dataset.messageId;
            console.log('Edit message clicked for message with ID:', messageId);
          });

          deleteLink.addEventListener('click', function(event) {
            event.preventDefault();
            var messageId = message.dataset.messageId;
            console.log('Delete message clicked for message with ID:', messageId);
          });
        }
      });

      function loadPreviousMessages() {
        var chatMessages = document.getElementById('chat-messages');
        var chatId = '{{ group_chat.id }}';
        var groupChatMessagesEndpoint = `/api/group-chats/${chatId}/`;

        fetch(groupChatMessagesEndpoint)
          .then(response => {
            if (!response.ok) {
              throw new Error(`HTTP error! Status: ${response.status}`);
            }
            return response.json();
          })
          .then(previousMessages => {
            if (previousMessages && previousMessages.length > 0) {
              previousMessages.forEach(message => {
                var messageDiv = document.createElement('div');
                messageDiv.classList.add('message');
                messageDiv.dataset.messageId = message.id;

                var avatarDiv = document.createElement('div');
                avatarDiv.classList.add('avatar');

                var img = document.createElement('img');
                img.src = message.sender.avatar ? message.sender.avatar.url : '';
                img.alt = message.sender.user.username;

                avatarDiv.appendChild(img);
                messageDiv.appendChild(avatarDiv);

                var messageContentDiv = document.createElement('div');
                messageContentDiv.classList.add('message-content');

                var paragraph = document.createElement('p');
                paragraph.innerHTML = `<strong>${message.sender.user.username}:</strong> ${message.content}`;

                var timestampSpan = document.createElement('span');
                timestampSpan.innerText = message.timestamp;

                messageContentDiv.appendChild(paragraph);
                messageContentDiv.appendChild(timestampSpan);

                if (message.sender.id === 4) {
                  var messageActionsDiv = document.createElement('div');
                  messageActionsDiv.classList.add('message-actions');

                  var editLink = document.createElement('a');
                  editLink.href = `${editMessageUrl}${message.id}/`;
                  editLink.classList.add('edit-link');
                  editLink.innerText = 'Редактировать';

                  var deleteLink = document.createElement('a');
                  deleteLink.href = `${deleteMessageUrl}${message.id}/`;
                  deleteLink.classList.add('delete-link');
                  deleteLink.innerText = 'Удалить';

                  messageActionsDiv.appendChild(editLink);
                  messageActionsDiv.appendChild(deleteLink);

                  messageContentDiv.appendChild(messageActionsDiv);
                }

                messageDiv.appendChild(messageContentDiv);
                chatMessages.appendChild(messageDiv);
              });
            }
          })
          .catch(error => console.error('Error loading previous messages:', error));
      }

      loadPreviousMessages();

      // WebSocket connection
      var chatSocket = new WebSocket(
        'ws://' + window.location.host +
        '/ws/chat/' + '{{ group_chat.id }}' + '/');

      chatSocket.onmessage = function(event) {
        var message = JSON.parse(event.data);
        var messageDiv = document.createElement('div');
        messageDiv.classList.add('message');
        messageDiv.dataset.messageId = message.id;

        var avatarDiv = document.createElement('div');
        avatarDiv.classList.add('avatar');

        var img = document.createElement('img');
        img.src = message.sender.avatar ? message.sender.avatar.url : '';
        img.alt = message.sender.user.username;

        avatarDiv.appendChild(img);
        messageDiv.appendChild(avatarDiv);

        var messageContentDiv = document.createElement('div');
        messageContentDiv.classList.add('message-content');

        var paragraph = document.createElement('p');
        paragraph.innerHTML = `<strong>${message.sender.user.username}:</strong> ${message.content}`;

        var timestampSpan = document.createElement('span');
        timestampSpan.innerText = message.timestamp;

        messageContentDiv.appendChild(paragraph);
        messageContentDiv.appendChild(timestampSpan);

        if (message.sender.id === 4) {
          var messageActionsDiv = document.createElement('div');
          messageActionsDiv.classList.add('message-actions');

          var editLink = document.createElement('a');
          editLink.href = `${editMessageUrl}${message.id}/`;
          editLink.classList.add('edit-link');
          editLink.innerText = 'Редактировать';

          var deleteLink = document.createElement('a');
          deleteLink.href = `${deleteMessageUrl}${message.id}/`;
          deleteLink.classList.add('delete-link');
          deleteLink.innerText = 'Удалить';

          messageActionsDiv.appendChild(editLink);
          messageActionsDiv.appendChild(deleteLink);

          messageContentDiv.appendChild(messageActionsDiv);
        }

        messageDiv.appendChild(messageContentDiv);
        chatMessages.appendChild(messageDiv);
      };

      // Form submission
      var messageForm = document.getElementById('message-form');

      messageForm.addEventListener('submit', function(event) {
        event.preventDefault();

        var formData = new FormData(messageForm);
        var content = formData.get('content');

        chatSocket.send(JSON.stringify({
          'content': content
        }));

        messageForm.reset();
      });
    });
  </script>
{% endblock %}